// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epxdydiznwhpojzbgftk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVweGR5ZGl6bndocG9qemJnZnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTE5NTgsImV4cCI6MjA2MjMyNzk1OH0.srjFsK_4RH7D3aZYBGJCTlHxqesG0RtrrntV9Xb2cGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);